DELETE http://localhost:5173/api/persons/2

###

GET http://localhost:5173/api/persons

###

POST http://localhost:5173/api/persons
Content-Type: application/json

{
  "name": "Claire Redfield",
  "phone": "040-439-3246"
}

###

POST http://localhost:5173/